apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-api
  namespace: default
  labels:
    app: payment-api
spec:
  replicas: 0
  selector:
    matchLabels:
      app: payment-api
  template:
    metadata:
      labels:
        app: payment-api
    spec:
      containers:
      - name: api
        image: polinux/stress-ng
        ports:
        - containerPort: 8080
        args:
        - --cpu
        - "1"
        
        # 🟢 1. LIMITES DE RECURSOS (Governança do Cluster)
        resources:
          requests:
            memory: "50Mi"
            cpu: "100m" # Garante 10% de 1 núcleo para iniciar
          limits:
            memory: "100Mi" # Se passar de 100Mi, o K8s dá OOMKilled para proteger o nó
            cpu: "200m"    # Se tentar usar mais de 20%, o K8s estrangula a CPU

        # 🟢 2. SONDAS DE SAÚDE (Ciclo de Vida)
        # Como o stress-ng não roda HTTP nativo, usamos sondas baseadas no processo interno
        readinessProbe:
          exec:
            command:
            - pgrep
            - stress-ng
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
            - pgrep
            - stress-ng
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: payment-api-service
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: payment-api
