apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-api
  namespace: default
  labels:
    app: payment-api
spec:
  replicas: 2 # Começamos com duas réplicas para garantir Alta Disponibilidade
  selector:
    matchLabels:
      app: payment-api
  template:
    metadata:
      labels:
        app: payment-api
    spec:
      containers:
      - name: api
        # Imagem perfeita de lab que responde na porta 8080 e nos permite simular testes de estresse
        image: vishnunielsen/stress
        ports:
        - containerPort: 8080
        
        # 🟢 1. LIMITES DE RECURSOS (Governança do Cluster)
        resources:
          requests:
            memory: "50Mi"
            cpu: "100m" # Garante 10% de 1 núcleo para iniciar
          limits:
            memory: "100Mi" # Se passar de 100Mi, o K8s dá OOMKilled para proteger o nó
            cpu: "200m"    # Se tentar usar mais de 20%, o K8s estrangula a CPU

        # 🟢 2. SONDAS DE SAÚDE (Ciclo de Vida)
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: payment-api-service
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: payment-api
